dex:
  enabled: false
global:
  domain: argocd.193.123.161.87.nip.io
configs:
  params:
    "server.insecure": true
server:
  ingress:
    enabled: true
    ingressClassName: nginx
controller:
  clusterRoleRules:
    enabled: true
    rules:
    - apiGroups:
        - '*'
      resources:
        - '*'
      verbs:
        - '*'