apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argo
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: manifests/wordpress
    repoURL: https://<GIT_HOST>/<YOUR_ACCOUNT>/fastcampus-cluster-gitops-practice.git
    targetRevision: HEAD